/**
 * @file: types.ts
 * @description: Core TypeScript interfaces and types for the application.
 * @dependencies: None
 * @created: 2025-12-15
 */


export interface CalendarEvent {
  id: number | string;
  seriesId?: string; // Identifies a group of recurring events
  title: string;
  start_time: string; // ISO String
  end_time?: string; // ISO String
  description?: string;
  user_id?: string;
  reminderMinutes?: number;
  recurrence?: 'daily' | 'weekly' | 'monthly' | 'yearly' | 'none';
  recurrenceInterval?: number; // E.g., 2 for "every 2 days"
  completed?: boolean;
  isAllDay?: boolean;
  category?: 'work' | 'personal' | 'health' | 'edu' | 'other';
  color?: string;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: number;
  isError?: boolean;
}

export enum AIActionType {
  CREATE = 'create',
  BATCH_CREATE = 'batch_create',
  UPDATE = 'update',
  DELETE = 'delete',
  READ = 'read',
  UNKNOWN = 'unknown'
}

export interface AIEventDetail {
  title: string;
  start_time: string;
  end_time?: string;
  description?: string;
  reminderMinutes?: number;
  recurrence?: 'daily' | 'weekly' | 'monthly' | 'yearly' | 'none';
  recurrenceInterval?: number;
  isAllDay?: boolean;
  color?: string;
}

export interface AIResponse {
  action: AIActionType;
  // Single event fields (kept for backward compatibility/single actions)
  title?: string;
  start_time?: string;
  end_time?: string;
  description?: string;
  reminderMinutes?: number;
  recurrence?: 'daily' | 'weekly' | 'monthly' | 'yearly' | 'none';
  recurrenceInterval?: number;
  isAllDay?: boolean;
  color?: string; // Hex code or category color

  // Batch event field
  events?: AIEventDetail[];

  original_query?: string;
  target_id?: string | number; // For updates/deletes if logic allows
  confirmation_message?: string; // Message generated by AI to show user
}

export interface AppState {
  events: CalendarEvent[];
  messages: ChatMessage[];
  isLoading: boolean;
}

export interface AISettings {
  telegramBotToken?: string;
  telegramChatId?: string;
  defaultReminderMinutes?: number;

  // AI Provider Settings
  provider: 'google' | 'algion' | 'openrouter' | 'custom';
  apiKey?: string; // Custom key for OpenRouter/Algion/Google
  baseUrl?: string; // For custom/Algion
  model?: string;   // e.g. 'gpt-4o', 'gemini-2.5-flash'
}